import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { SceneLayout } from '../../../SceneLayout';

export const Scene03_RangeFunction: React.FC = () => {
  const [start, setStart] = useState(0);
  const [end, setEnd] = useState(10);
  const [step, setStep] = useState(1);

  const values = useMemo(() => {
    const result: number[] = [];

    if (step === 0) return result;

    if (step > 0) {
      for (let i = start; i < end; i += step) {
        result.push(i);
      }
    } else {
      for (let i = start; i > end; i += step) {
        result.push(i);
      }
    }

    return result;
  }, [start, end, step]);

  return (
    <SceneLayout gap="gap-5">
      {/* Header */}
      <div>
        <span className="text-sm font-mono uppercase tracking-widest text-indigo-600 font-extrabold">
          Lesson 5.3 · Repeating Work Automatically
        </span>

        <h2 className="text-3xl lg:text-4xl font-extrabold text-slate-800 mt-1">
          The{' '}
          <span className="text-indigo-600 font-serif italic">
            range()
          </span>{' '}
          Function
        </h2>

        <p className="text-sm text-slate-500 mt-1 max-w-3xl">
          Experiment with start, stop, and step values to discover how
          Python generates sequences using range().
        </p>
      </div>

      <div className="flex-1 flex gap-5 min-h-0">

        {/* Controls */}
        <div className="w-[380px] shrink-0 flex flex-col gap-4">

          {/* Start */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4">
            <div className="flex justify-between">
              <div className="text-xs font-mono font-bold text-slate-400 uppercase">
                Start
              </div>

              <div className="font-black text-indigo-600">
                {start}
              </div>
            </div>

            <input
              type="range"
              min={-10}
              max={20}
              value={start}
              onChange={(e) =>
                setStart(Number(e.target.value))
              }
              className="w-full mt-4"
            />
          </div>

          {/* Stop */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4">
            <div className="flex justify-between">
              <div className="text-xs font-mono font-bold text-slate-400 uppercase">
                Stop
              </div>

              <div className="font-black text-orange-600">
                {end}
              </div>
            </div>

            <input
              type="range"
              min={-10}
              max={20}
              value={end}
              onChange={(e) =>
                setEnd(Number(e.target.value))
              }
              className="w-full mt-4"
            />
          </div>

          {/* Step */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4">
            <div className="flex justify-between">
              <div className="text-xs font-mono font-bold text-slate-400 uppercase">
                Step
              </div>

              <div className="font-black text-emerald-600">
                {step}
              </div>
            </div>

            <input
              type="range"
              min={-5}
              max={5}
              value={step}
              onChange={(e) => {
                const value = Number(e.target.value);
                setStep(value === 0 ? 1 : value);
              }}
              className="w-full mt-4"
            />
          </div>

          {/* Python */}
          <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-4">

            <div className="text-xs font-mono font-bold text-indigo-600 uppercase">
              Python Code
            </div>

            <pre className="mt-3 text-sm font-mono font-bold text-slate-800 whitespace-pre-wrap">
{`numbers = range(${start}, ${end}, ${step})

for i in numbers:
    print(i)`}
            </pre>

          </div>

        </div>

        {/* Visualization */}
        <div className="flex-1 flex flex-col gap-5">

          <div className="flex-1 bg-slate-50 border border-slate-200 rounded-3xl p-6">

            <div className="text-xs font-mono font-bold text-slate-400 uppercase tracking-widest">
              Values Generated By range()
            </div>

            <div className="flex-1 flex items-center justify-center">

              {values.length === 0 ? (
                <div className="text-center">
                  <div className="text-5xl">⚠️</div>

                  <div className="mt-3 text-2xl font-black text-red-500">
                    No Values Generated
                  </div>

                  <div className="mt-2 text-slate-500 font-semibold">
                    These start/stop/step values don't produce a sequence.
                  </div>
                </div>
              ) : (
                <div className="flex flex-wrap justify-center gap-4 max-w-5xl">

                  {values.map((value, index) => (
                    <motion.div
                      key={`${value}-${index}`}
                      initial={{
                        opacity: 0,
                        scale: 0.9
                      }}
                      animate={{
                        opacity: 1,
                        scale: 1
                      }}
                      className="relative"
                    >
                      <div className="absolute -top-6 left-1/2 -translate-x-1/2 text-xs font-black text-slate-400">
                        #{index}
                      </div>

                      <div className="w-24 h-24 rounded-3xl bg-white border-2 border-indigo-500 flex items-center justify-center">
                        <span className="text-4xl font-black text-indigo-600">
                          {value}
                        </span>
                      </div>
                    </motion.div>
                  ))}

                </div>
              )}

            </div>

          </div>

          {/* Summary */}
          <div className="grid grid-cols-4 gap-4">

            <div className="bg-white border border-slate-200 rounded-2xl p-4 text-center">
              <div className="text-xs font-mono uppercase text-slate-400">
                First Value
              </div>

              <div className="mt-2 text-3xl font-black text-indigo-600">
                {values.length ? values[0] : '-'}
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-2xl p-4 text-center">
              <div className="text-xs font-mono uppercase text-slate-400">
                Last Value
              </div>

              <div className="mt-2 text-3xl font-black text-orange-600">
                {values.length
                  ? values[values.length - 1]
                  : '-'}
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-2xl p-4 text-center">
              <div className="text-xs font-mono uppercase text-slate-400">
                Step Size
              </div>

              <div className="mt-2 text-3xl font-black text-emerald-600">
                {step}
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-2xl p-4 text-center">
              <div className="text-xs font-mono uppercase text-slate-400">
                Total Values
              </div>

              <div className="mt-2 text-3xl font-black text-slate-800">
                {values.length}
              </div>
            </div>

          </div>

        </div>

      </div>
    </SceneLayout>
  );
};

export default Scene03_RangeFunction;